# Załadowanie środowiska --------------------------------------------------
.libPaths(c('/home/mkosinski/R/x86_64-pc-linux-gnu-library/3.2', .libPaths()))
library(rvest)
library(stringi)
library(stringr)
library(RSQLite)
library(RSelenium)
library(httr)
#library(purrr)
library(pbapply)
library(ggmap)
library(stringdist)
library(data.table)
library(dplyr)
# library(ggplot2)
# library(ggthemes)
library(tidyr)